drop table DEPARTMENT if exists;

CREATE TABLE DEPARTMENT
(
  ID BIGINT IDENTITY PRIMARY KEY
, NAME VARCHAR2(50) NOT NULL
, DANE_CODE VARCHAR2(50)
, VERSION INT
, CREATED_AT TIMESTAMP NOT NULL
, MODIFIED_AT TIMESTAMP NOT NULL
);
